"""initial

Revision ID: 51e12d5fa70d
Revises: 
Create Date: 2026-05-05 18:30:16.486620
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '51e12d5fa70d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('rfc', sa.String(length=13), nullable=True),
    sa.Column('razon_social', sa.String(length=255), nullable=True),
    sa.Column('regimen_fiscal', sa.String(length=8), nullable=True),
    sa.Column('codigo_postal', sa.String(length=5), nullable=True),
    sa.Column('uso_cfdi_default', sa.String(length=8), nullable=True),
    sa.Column('correo', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=32), nullable=True),
    sa.Column('whatsapp', sa.String(length=32), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('limite_credito', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('dias_credito', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_nombre'), 'clientes', ['nombre'], unique=False)
    op.create_index(op.f('ix_clientes_rfc'), 'clientes', ['rfc'], unique=False)
    op.create_index(op.f('ix_clientes_whatsapp'), 'clientes', ['whatsapp'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=120), nullable=True),
    sa.Column('marca', sa.String(length=120), nullable=True),
    sa.Column('clave_prod_serv_sat', sa.String(length=8), nullable=True),
    sa.Column('objeto_impuesto_sat', sa.String(length=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_categoria'), 'productos', ['categoria'], unique=False)
    op.create_index(op.f('ix_productos_nombre'), 'productos', ['nombre'], unique=False)
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('rfc', sa.String(length=13), nullable=True),
    sa.Column('razon_social', sa.String(length=255), nullable=True),
    sa.Column('correo', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=32), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('dias_credito', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proveedores_nombre'), 'proveedores', ['nombre'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=32), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio_interno', sa.String(length=32), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('uuid_cfdi', sa.String(length=40), nullable=True),
    sa.Column('folio_factura_proveedor', sa.String(length=40), nullable=True),
    sa.Column('fecha_factura', sa.DateTime(), nullable=True),
    sa.Column('fecha_recepcion', sa.DateTime(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estatus', sa.String(length=16), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio_interno'),
    sa.UniqueConstraint('uuid_cfdi')
    )
    op.create_index(op.f('ix_compras_proveedor_id'), 'compras', ['proveedor_id'], unique=False)
    op.create_table('documentos_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=32), nullable=False),
    sa.Column('tipo', sa.String(length=16), nullable=False),
    sa.Column('estatus', sa.String(length=16), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('forma_pago_sat', sa.String(length=2), nullable=False),
    sa.Column('metodo_pago_sat', sa.String(length=3), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('uso_cfdi', sa.String(length=8), nullable=True),
    sa.Column('factura_padre_id', sa.Integer(), nullable=True),
    sa.Column('factura_relacionada_id', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['factura_padre_id'], ['documentos_venta.id'], ),
    sa.ForeignKeyConstraint(['factura_relacionada_id'], ['documentos_venta.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_venta_cliente_id'), 'documentos_venta', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_documentos_venta_factura_padre_id'), 'documentos_venta', ['factura_padre_id'], unique=False)
    op.create_index(op.f('ix_documentos_venta_fecha'), 'documentos_venta', ['fecha'], unique=False)
    op.create_index(op.f('ix_documentos_venta_folio'), 'documentos_venta', ['folio'], unique=True)
    op.create_index('ix_docventa_cliente_estatus', 'documentos_venta', ['cliente_id', 'estatus'], unique=False)
    op.create_index('ix_docventa_tipo_fecha', 'documentos_venta', ['tipo', 'fecha'], unique=False)
    op.create_table('variantes_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('presentacion', sa.String(length=64), nullable=False),
    sa.Column('unidad', sa.String(length=32), nullable=False),
    sa.Column('clave_unidad_sat', sa.String(length=3), nullable=False),
    sa.Column('precio_publico', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('precio_mayoreo', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('cantidad_mayoreo', sa.Integer(), nullable=False),
    sa.Column('costo_promedio', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('stock_actual', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('stock_minimo', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('derivada_id', sa.Integer(), nullable=True),
    sa.Column('factor_division', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['derivada_id'], ['variantes_producto.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variantes_producto_sku'), 'variantes_producto', ['sku'], unique=True)
    op.create_table('cfdis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_venta_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=40), nullable=False),
    sa.Column('serie', sa.String(length=10), nullable=False),
    sa.Column('folio', sa.String(length=20), nullable=False),
    sa.Column('fecha_timbrado', sa.DateTime(), nullable=False),
    sa.Column('rfc_emisor', sa.String(length=13), nullable=False),
    sa.Column('rfc_receptor', sa.String(length=13), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tipo_comprobante', sa.String(length=1), nullable=False),
    sa.Column('xml_url', sa.String(length=500), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('cancelado', sa.Boolean(), nullable=False),
    sa.Column('motivo_cancelacion', sa.String(length=2), nullable=True),
    sa.Column('uuid_sustituye', sa.String(length=40), nullable=True),
    sa.Column('fecha_cancelacion', sa.DateTime(), nullable=True),
    sa.Column('respuesta_pac', sa.JSON(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['documento_venta_id'], ['documentos_venta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento_venta_id')
    )
    op.create_index(op.f('ix_cfdis_uuid'), 'cfdis', ['uuid'], unique=True)
    op.create_table('conceptos_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('importe', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['compra_id'], ['compras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variante_id'], ['variantes_producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conceptos_compra_compra_id'), 'conceptos_compra', ['compra_id'], unique=False)
    op.create_table('conceptos_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('importe', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('clave_prod_serv_sat', sa.String(length=8), nullable=True),
    sa.Column('clave_unidad_sat', sa.String(length=3), nullable=True),
    sa.Column('tasa_iva', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos_venta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variante_id'], ['variantes_producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conceptos_venta_documento_id'), 'conceptos_venta', ['documento_id'], unique=False)
    op.create_table('cotizaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=32), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('whatsapp_origen', sa.String(length=32), nullable=True),
    sa.Column('nombre_libre', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('vigencia_hasta', sa.DateTime(), nullable=True),
    sa.Column('conceptos', sa.JSON(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estatus', sa.String(length=16), nullable=False),
    sa.Column('documento_venta_id', sa.Integer(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['documento_venta_id'], ['documentos_venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cotizaciones_cliente_id'), 'cotizaciones', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_cotizaciones_folio'), 'cotizaciones', ['folio'], unique=True)
    op.create_table('cuentas_por_cobrar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('monto_original', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('pagado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos_venta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento_id')
    )
    op.create_index(op.f('ix_cuentas_por_cobrar_cliente_id'), 'cuentas_por_cobrar', ['cliente_id'], unique=False)
    op.create_table('cuentas_por_pagar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('monto_original', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('pagado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['compra_id'], ['compras.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('compra_id')
    )
    op.create_index(op.f('ix_cuentas_por_pagar_proveedor_id'), 'cuentas_por_pagar', ['proveedor_id'], unique=False)
    op.create_table('movimientos_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=32), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('referencia_tipo', sa.String(length=32), nullable=True),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['variante_id'], ['variantes_producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mov_variante_fecha', 'movimientos_inventario', ['variante_id', 'fecha'], unique=False)
    op.create_index(op.f('ix_movimientos_inventario_fecha'), 'movimientos_inventario', ['fecha'], unique=False)
    op.create_index(op.f('ix_movimientos_inventario_variante_id'), 'movimientos_inventario', ['variante_id'], unique=False)
    op.create_table('abonos_cxc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cxc_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('forma_pago', sa.String(length=32), nullable=False),
    sa.Column('referencia', sa.String(length=120), nullable=True),
    sa.Column('origen', sa.String(length=32), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cxc_id'], ['cuentas_por_cobrar.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abonos_cxc_cxc_id'), 'abonos_cxc', ['cxc_id'], unique=False)
    op.create_table('abonos_cxp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cxp_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('forma_pago', sa.String(length=32), nullable=False),
    sa.Column('referencia', sa.String(length=120), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cxp_id'], ['cuentas_por_pagar.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abonos_cxp_cxp_id'), 'abonos_cxp', ['cxp_id'], unique=False)
    op.create_table('complementos_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cfdi_origen_id', sa.Integer(), nullable=False),
    sa.Column('abono_cxc_id', sa.Integer(), nullable=True),
    sa.Column('uuid_complemento', sa.String(length=40), nullable=False),
    sa.Column('monto_pagado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=False),
    sa.Column('forma_pago_sat', sa.String(length=2), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('xml_url', sa.String(length=500), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['abono_cxc_id'], ['abonos_cxc.id'], ),
    sa.ForeignKeyConstraint(['cfdi_origen_id'], ['cfdis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid_complemento')
    )
    op.create_index(op.f('ix_complementos_pago_cfdi_origen_id'), 'complementos_pago', ['cfdi_origen_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complementos_pago_cfdi_origen_id'), table_name='complementos_pago')
    op.drop_table('complementos_pago')
    op.drop_index(op.f('ix_abonos_cxp_cxp_id'), table_name='abonos_cxp')
    op.drop_table('abonos_cxp')
    op.drop_index(op.f('ix_abonos_cxc_cxc_id'), table_name='abonos_cxc')
    op.drop_table('abonos_cxc')
    op.drop_index(op.f('ix_movimientos_inventario_variante_id'), table_name='movimientos_inventario')
    op.drop_index(op.f('ix_movimientos_inventario_fecha'), table_name='movimientos_inventario')
    op.drop_index('ix_mov_variante_fecha', table_name='movimientos_inventario')
    op.drop_table('movimientos_inventario')
    op.drop_index(op.f('ix_cuentas_por_pagar_proveedor_id'), table_name='cuentas_por_pagar')
    op.drop_table('cuentas_por_pagar')
    op.drop_index(op.f('ix_cuentas_por_cobrar_cliente_id'), table_name='cuentas_por_cobrar')
    op.drop_table('cuentas_por_cobrar')
    op.drop_index(op.f('ix_cotizaciones_folio'), table_name='cotizaciones')
    op.drop_index(op.f('ix_cotizaciones_cliente_id'), table_name='cotizaciones')
    op.drop_table('cotizaciones')
    op.drop_index(op.f('ix_conceptos_venta_documento_id'), table_name='conceptos_venta')
    op.drop_table('conceptos_venta')
    op.drop_index(op.f('ix_conceptos_compra_compra_id'), table_name='conceptos_compra')
    op.drop_table('conceptos_compra')
    op.drop_index(op.f('ix_cfdis_uuid'), table_name='cfdis')
    op.drop_table('cfdis')
    op.drop_index(op.f('ix_variantes_producto_sku'), table_name='variantes_producto')
    op.drop_table('variantes_producto')
    op.drop_index('ix_docventa_tipo_fecha', table_name='documentos_venta')
    op.drop_index('ix_docventa_cliente_estatus', table_name='documentos_venta')
    op.drop_index(op.f('ix_documentos_venta_folio'), table_name='documentos_venta')
    op.drop_index(op.f('ix_documentos_venta_fecha'), table_name='documentos_venta')
    op.drop_index(op.f('ix_documentos_venta_factura_padre_id'), table_name='documentos_venta')
    op.drop_index(op.f('ix_documentos_venta_cliente_id'), table_name='documentos_venta')
    op.drop_table('documentos_venta')
    op.drop_index(op.f('ix_compras_proveedor_id'), table_name='compras')
    op.drop_table('compras')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_proveedores_nombre'), table_name='proveedores')
    op.drop_table('proveedores')
    op.drop_index(op.f('ix_productos_nombre'), table_name='productos')
    op.drop_index(op.f('ix_productos_categoria'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_clientes_whatsapp'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_rfc'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_nombre'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
